sudo: false
language: python

branches:
  except:
  - gh-pages
  - legacy
  - experimental

python:
- "3.6"

install:
- pip install tox-travis
- pip install codecov coverage


script:
- tox

after_success:
- coverage combine && codecov


deploy:
  provider: pages
  skip-cleanup: true
  github-token: 5d38629731dd757d2beadfab9e44a42156dc923d
  keep-history: true
  on:
    branch: master