sudo: false
language: python

branches:
  except:
  - gh-pages

python:
#- "2.7"
- "3.4"

install:
- pip install tox-travis
- pip install codecov
- pip install coverage

script:
- tox

after_success:
- coverage combine && codecov

stages:
- test
- name: deploy
  if: tag IS present

jobs:
  include:
  - python: 3.6
    env: TOXENV=docs
  - python: 3.6
    env: TOXENV=desc