sudo: false
language: python

branches:
  except:
  - gh-pages
  - legacy
  - experimental

python:
- "3.6"

install:
- pip install tox-travis
- pip install codecov coverage


script:
- tox

after_success:
- coverage combine && codecov
