language: python

sudo: false

cache: pip

python:
- "3.6"


env:
  matrix:
  - COVERAGE_COVERAGE=no
  - COVERAGE_COVERAGE=yes

install:
- pip install tox-travis
- pip install codecov

script:
- tox

after_success:
  -codecov