sudo: false
language: python

python:
- "3.6"

install:
- pip install tox-travis
- pip install codecov

script:
- tox

after_success: coverage combine && codecov

stages:
- test
- name: deploy
  if: tag IS present

jobs:
  include:
  - python: 3.6
    env: TOXENV=docs
  - python: 3.6
    env: TOXENV=desc
