sudo: false
language: python

python:
- "3.5"
- "3.6"

install:
- pip install tox
#- pip install tox-travis
- pip install codecov
- pip install coverage

script:
- tox

after_success:
- coverage combine && codecov
